apiVersion: v1
kind: ConfigMap
metadata:
  name: "config-nginx"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
data:
  # /etc/nginx.conf
  nginx.conf: |-
    #daemon                 off;
    pid                    /tmp/nginx.pid;
    worker_processes       auto;
    worker_rlimit_nofile   65535;
    #
    events {
      multi_accept         on;
      worker_connections   65535;
    }
    #
    http {
      charset              utf-8;
      sendfile             on;
      tcp_nopush           on;
      tcp_nodelay          on;
      server_tokens        off;
      log_not_found        off;
      types_hash_max_size  2048;
    #
      # MIME
      include mime.types;
      default_type         text/html;
    #
      # Logging
      # Uncomment if you want access logs on stdout
      #access_log           /dev/stdout;
      access_log           off;
      error_log            /dev/stdout notice;
    #
      server {
        listen             8000;
        server_name        _;
        root               /var/www/static;
    #
    #
        location / {
          rewrite ^(.*) /index.php$1 last;
      }
    #
        location ~ ^/index\.php(/|$) {
          if ($request_method = OPTIONS) {
            return 200;
          }
    #
          proxy_buffer_size          128k;
          proxy_buffers              4 256k;
          proxy_busy_buffers_size    256k;
    #
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          internal;
    #
          # default fastcgi params
          include             fastcgi_params;
    #
          # fastcgi settings
          fastcgi_index             index.php;
          fastcgi_buffer_size       128k;
          fastcgi_buffers           4 256k;
    #
          # fastcgi params
          fastcgi_param DOCUMENT_ROOT   /var/www;
          fastcgi_param SCRIPT_NAME     /index.php;
          fastcgi_param SCRIPT_FILENAME /var/www/index.php;
        }
      #
      #  return 404;
      }
    }

  # /var/www/static/healthz.html
  healthz.html: |-
    <html><p>Health OK</html>
