apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
    - port: 8000
      name: http
      targetPort: http
  selector:
    app: {{ .Values.app.name }}
---
